---
title: "MATP-4910  Final Project Notebook Template"
author: "Student Name"
date: "15 November 2021"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
subtitle: "DAR Project (One of: DeFi, Match2, Eat4Genes)"
---

## Instructions (DELETE BEFORE SUBMISSION)

Your notebook serves as a written presentation of your work this semester so it should be written like a research paper.

* The rubric for evaluating this project is on LMS.
* The R code that executes the results should be embedded in this notebook if possible. 
    + It's also okay to "source" external scripts from within your notebook, including those provided by your instructors. 
* Fall 2021 students may have work that is not appropriate to be embedded on your final notebook
    + You should describe the work in the notebook and provide figures generated elsewhere (e.g. screen shots, graphs). 
    + Indicate if that work has been committed to github. If necessary put details in Appendix.    
* Your wording should be suitable for sharing with external partners/mentors and useful to future contributors.
* Please don't summarize everything you did this semester
    + Discuss only the *most important* aspects of your work. 
    + Ask yourself *what really matters?*
* **IMPORTANT:** Discuss any insights you found regarding DeFi or Eat-4-Genes.
* If there are limitations to your work, discuss. 
* Include any **background** or **supporting evidence** for your work. 
    + For example, mention any relevant research articles you found -- and be sure to include references!
* Include your recommendations for continuing or extending your project
    + Data utilization...
    + Analytics...
    + Visualizations
    + User interface design...
    + Apps...
    + Open questions that could be investigated...
    
## NOTEBOOK SUBMISSION CHECKLIST: Things to check before you submit (DELETE) ##

* Have you given your file(s) a clear, sensible name? 
     + `my_notebook.Rmd` or `joey.Rmd` are **not* acceptable!
* Is every figure clearly labeled and titled? 
* Does every figure serve a purpose? 
     + What question does it answer? 
     + You can put extra (non-essential) figures in your **Appendix**.
* Are your tables clearly labeled and legible?
     + We recommend using `kable()` (built into `knitr`) or the `gt` ("Grammar of Tables") package
     + `xtable()` might also work for you (not as easy as `kable()` and not as elegant as `gt`) 
* **CRITICAL:** Have you given enough information for someone to reproduce, understand and extend your results?
     + Where can they *find* the data that you used?
     + Have you *described* the data that used?
     + Have you *documented* your code? 
     + Are your figures *clearly labeled*?
     + Did you *discuss your findings*?
     + Did you use good grammar and *proofread* your results?
     + Finally, have you *committed* your work to github and made a *pull request*?
     + Did you indicate the github *issues* that you addressed? 


* Use this notebook is a template for your FINAL project notebook. 
* Use the sections starting with **Work Summary** as your outline for your submitted notebook.
* Summarize ALL of your work that is worthy of being preserved in this notebook; **if you don't show and/or link to your work here, it doesn't exist for us!**

## Instructions: Submitting a Notebook via github (DELETE BEFORE SUBMISSION)


1. Create a new copy of this notebook in the appropriate assignment sub-directory of your team's github repository using the following naming convention

   * `dar_final_rcsid_ddmmmyyyy.Rmd` and `dar_final_rcsid_ddmmmyyyy.html`
   * For example, `dar_final_erickj4_1nov2021.Rmd`
   
2. Delete the instructions.

3. You **MUST** include figures and/or tables to illustrate your work. *Screen shots are okay*; exported PNGs are preferred.

4. You **MUST** include links to other important resources (knitted HTMl files, Shiny apps). See the guide below for help.

5. Commit the source (`.Rmd`), pdf (`.pdf`) and knitted (`.html`) versions of your notebook and push to github. Turn in the pdf version to lms. 

6. **Submit a pull request.** Please notify Dr. Erickson if you don't see your notebook merged within one day. 

7. **DO NOT MERGE YOUR PULL REQUESTS YOURSELF!!**

See LMS for guidance on how the contents of this notebook will be graded.

**DELETE THE SECTIONS ABOVE!**

# Final Project: Github Info

*This should be the first section of your final project notebook. Fill out the following according to how you submitted your notebook!*

* github repository: 
* Your github ID: _erickj4_ (example)
* Final notebook: *dar_final_erickj4_1nov2021.Rmd* (example)
    
* Summary of github contributions including github issues addressed.

    * Include browsable links to all external files on github
    * Include links to shared Shiny apps
    * Include list of github issues addressed. 
    * A detailed summary of branches is not required for the final report
    
* List of presentations,  papers, or other outputs

    * Include browsable links!
    
* List of references (if necessary) 
* Indicate any use of group shared code base
* Indicate which parts of your described work were done by you or as part of joint efforts

# Overview & Problems Tackled

*Provide a top-level summary of your work and findings.*

# Data Description

*Include data sources/locations, versions/dates, etc.. Indicate the size of your data - how many data points, how many features etc.   If you spent time preparing data, you can discuss it here as a subsection or if appropriate put in methods.* 

# Results

*Break out your results by each problem you attacked. Note that if you spent lots of time on Eat4Genes preparing data and haven't thought about, then write up case studies for using the app. *

## Problem 1 

*Describe the problem you are examining.  If there is background that is necessary for this problem, then put it here. Include any references.* 

 
### Methods

*How did you address the problem? What data did you use exactly? What methods did you use?* 

	
### Results

*What were the results on this problem?*


### Discussion

*Interpret results.  What were your findings?  What do they say about in terms of the original domain (e.g. DeFi or health eating)?   What are the strengths and limitations of these results? Is there support for your findings from other sources? Include references as appropriate.*

## Problem 2
 
### Methods
	
### Results

### Discussion

*Do at least 2 problems. Add more as necessary *


# Summary and Recommendations

* Overall, what insights did you find  about (DeFi, Eat-4-genes) in your analysis?    

* What recommendations do you have for future work for  future studies, Data utilization, Analytics, Visualizations, User interface design, New features, etc.
    + Would you recommend that your analysis be included in an expanded app or paper?  Why or Why not?  
    + If not, is there additional work that might  improve the results?  Note that it is perfectly okay for you to recommend to not to include your analysis. Research doesn't always work out.  As a team we need to try a lot of different ideas in hopes of finding a few good ones to pursue.  *

* Think of yourself as a consultant reporting back on a particular aspect of the analysis and application design!*

# References

*Include any references to literature in support of your work*
*You might also wish to include references to unusual R packages essential to your work*

# Appendix

*Include here whatever you think is relevant to support the main content of your notebook. For example, you may have only include example figures above in your main text but include additional ones here* 




